
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: skyline_emporium


test:
  <<: *default
  database: skyline_emporium-test

production:
  <<: *default
  database: skyline_emporium-prod
